language: ruby

rvm:
  - 2.4.1

gemfile:
  - gemfiles/Gemfile-4-2-stable

env:
  global:
    - JRUBY_OPTS=--dev
    - TEST_SUITE=test

sudo: false

before_script:
  - RAILS_ENV=test bundle exec rake --rakefile=test/dummy/Rakefile db:setup

script:
  - bundle exec rake ${TEST_SUITE}

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
    - rvm: jruby
    - gemfile: Gemfile
